trigger: none

variables:
  configpath: "$(System.DefaultWorkingDirectory)/Nested map/Parent Module"

stages:
# ---------- Terraform Plan ----------
- stage: TerraformPlan
  displayName: "Terraform Plan"
  jobs:
  - job: plan
    displayName: "Run Terraform Plan"
    pool: apna-agent-pool
      
    steps:
    - task: TerraformTaskV4@4
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(configpath)

    - task: TerraformTaskV4@4
      displayName: "Terraform Plan"
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: $(configpath)
        environmentServiceNameAzureRM: 'next-level-service-connection'

# ---------- Manual Approval ----------
- stage: Approval
  displayName: "Approval Before Apply"
  dependsOn: TerraformPlan
  jobs:
  - job: waitForApproval
    displayName: "Manual Approval Required"
    pool: server
    timeoutInMinutes: 120  # 2 ghante me approve karna hoga
    steps:
    - task: ManualValidation@1
      inputs:
        instructions: |
          ✅ Terraform plan output check karo.
          ❌ Agar kuch galat ho to reject karo.
        onTimeout: 'reject'

# ---------- Terraform Apply ----------
- stage: TerraformApply
  displayName: "Terraform Apply"
  dependsOn: Approval
  jobs:
  - job: apply
    displayName: "Run Terraform Apply"
    pool: apna-agent-pool
     
    steps:
    - task: TerraformTaskV4@4
      displayName: "Terraform Apply"
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: $(configpath)
        environmentServiceNameAzureRM: 'next-level-service-connection'
