trigger:
  branches:
    include:
     - main
     - feature/*
parameters:
  - name: planrequired
    displayName: planrequired
    type: string
    values:
      - true
      - false

pool: docker-agent
variables:
  configuepath: '$(System.DefaultWorkingDirectory)/environment/dev'

stages:
# Stage 1: Terraform Init & Plan
- stage: init_and_plan
  jobs:
    - job: terraform_plan
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'

      - task: TerraformTaskV4@4
        inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(configuepath)'
            backendAzureRmResourceGroupName: 'rg-it'
            backendServiceArm: 'next-level-service-connection'
            backendAzureRmStorageAccountName: 'itsolution'
            backendAzureRmContainerName: 'nextlevelcontainer'
            backendAzureRmKey: 'itit.tfstate'
- stage: manual validation
  displayName: Manual validation
  jobs:
    - job:
      displayName: Manual validation
      pool: server
      steps:
      - task: ManualValidation@1
        inputs:
          notifyUsers: 'ajaykumaryadav97@gmail.com'
          approvers: 'ajaykumaryadav97@gmail.com'
          instructions: 'Approval do sir'
          onTimeout: 'resume'

      - task: TerraformTaskV4@4
        inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(configuepath)'
            environmentServiceNameAzureRM: 'next-level-service-connection'

# Stage 2: Terraform Apply with Approval
- stage: Apply
  dependsOn: init_and_plan
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:
    - job: terraformapply
      displayName: terraform apply
      pool: docker-agent
      steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'echo Terraform apply runs only from main branch'
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(configuepath)'
          environmentServiceNameAzureRM: 'next-level-service-connection'

