trigger: none

pool: apna-agent

steps:
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
    backendServiceArm: 'next-level-service-connection'
    backendAzureRmStorageAccountName: 'itsolution'
    backendAzureRmContainerName: 'nextlevelcontainer'
    backendAzureRmKey: 'itit.tfstate'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
    environmentServiceNameAzureRM: 'next-level-service-connection'